/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_JNITest_Hello */

#ifndef _Included_com_example_finalandroid_JNI
#define _Included_com_example_finalandroid_JNI
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_com_example_finalandroid_Segment
  (JNIEnv *, jobject, jstring, jstring, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
